/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author aluno
 */
public class TelaAnimais extends javax.swing.JFrame {

    /**
     * Creates new form TelaAnimais
     */
    public TelaAnimais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        btRita = new javax.swing.JButton();
        btMu = new javax.swing.JButton();
        btClebinho = new javax.swing.JButton();
        btLuigi = new javax.swing.JButton();
        btPacoca = new javax.swing.JButton();
        btXica = new javax.swing.JButton();
        btDogFiltro1 = new javax.swing.JButton();
        btCatFiltro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pagina Inicial.png"))); // NOI18N
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(btRita, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 200, 200));
        jPanel1.add(btMu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 200, 200));
        jPanel1.add(btClebinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 210, 200));
        jPanel1.add(btLuigi, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, 210, 200));
        jPanel1.add(btPacoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 210, 200));
        jPanel1.add(btXica, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 210, 200));
        jPanel1.add(btDogFiltro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, 60));
        jPanel1.add(btCatFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAnimais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCatFiltro;
    private javax.swing.JButton btClebinho;
    private javax.swing.JButton btDogFiltro1;
    private javax.swing.JButton btLuigi;
    private javax.swing.JButton btMu;
    private javax.swing.JButton btPacoca;
    private javax.swing.JButton btRita;
    private javax.swing.JButton btXica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
